Tellers/Tellers.App/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System.Security.Claims;
using Tellers.Services.Interfaces;
using Tellers.ViewModels.Profiles;

namespace Tellers.App.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProfileService profileService;

        public ProfileController(IProfileService profileService)
        {
            this.profileService = profileService;
        }

        [Authorize]
        public async Task<IActionResult> Info(string profileId)
        {
            return View(await this.profileService.GetProfileInfo(profileId, User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }
    }
}

Tellers/Tellers.App/Controllers/RevueController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Tellers.Services.Interfaces;
using Tellers.Utilities;
using Tellers.ViewModels.Revues;

namespace Tellers.App.Controllers
{
    public class RevueController : Controller
    {
        private const string fragment = "revues";
        private readonly IRevueService revueService;
        private readonly IProfileService profileService;

        public RevueController(
            IRevueService revueService,
            IProfileService profileService)
        {
            this.revueService = revueService;
            this.profileService = profileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(string storyId)
        {
            var profile = await profileService.GetProfile(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = new CreateRevueViewModel()
            {
                StoryId = storyId,
                CreatorPictureUrl = profile.PictureUrl,
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(string storyId, CreateRevueViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await revueService.CreateRevue(model.StoryId, User.FindFirstValue(ClaimTypes.NameIdentifier), model.Text, model.Rating);

            var redirectResult = RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });

            redirectResult.Fragment = fragment;
            return redirectResult;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int revueId, string storyId, string userId)
        {
            var revueCreatorId = await this.revueService.GetRevueCreatorId(revueId);

            if (User.FindFirstValue(ClaimTypes.NameIdentifier) != revueCreatorId && User.FindFirstValue(ClaimTypes.NameIdentifier) != userId)
            {
                return RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });
            }

            var model = await this.revueService.GetRevueForEditing(revueId);

            if (model == null)
            {
                return NotFound();
            }

            var profile = await this.profileService.GetProfile(userId);

            if(profile == null)
            {
                return NotFound();
            }

            model.CreatorPictureUrl = profile.PictureUrl;
            model.StoryId = storyId;
            model.UserId = userId;
            model.Id = revueId;

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(string storyId, string userId, int revueId, EditRevueViewModel model)
        {
            var revueCreatorId = await this.revueService.GetRevueCreatorId(revueId);

            if (User.FindFirstValue(ClaimTypes.NameIdentifier) != revueCreatorId && User.FindFirstValue(ClaimTypes.NameIdentifier) != userId)
            {
                return RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });
            }

            if (!ModelState.IsValid)
            {
                var profile = await profileService.GetProfile(userId);
                model.CreatorPictureUrl = profile.PictureUrl;
                model.Id = revueId;
                return View(model);
            }

            await this.revueService.EditRevue(revueId, model.Text, model.Rating);

            var redirectResult = RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });
            redirectResult.Fragment = fragment;
            return redirectResult;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(string storyId, int revueId)
        {
            var revueCreatorId = await this.revueService.GetRevueCreatorId(revueId);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId != revueCreatorId)
            {
                return RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });
            }
            await this.revueService.DeleteRevue(revueId);

            return RedirectToAction(nameof(StoryController.Read), nameof(StoryController).ReplaceControllerSuffix(), new { storyId = storyId });
        }
    }
}

Tellers/Tellers.App/Controllers/StoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using Tellers.Services.Interfaces;
using Tellers.ViewModels.Story;

namespace Tellers.App.Controllers
{
    public class StoryController : Controller
    {
        private readonly IStoryService storyService;
        private readonly IGenreService genreService;
        private readonly IStoryTypeService storyTypeService;

        public StoryController(
            IStoryService storyService,
            IGenreService genreService,
            IStoryTypeService storyTypeService)
        {
            this.storyService = storyService;
            this.genreService = genreService;
            this.storyTypeService = storyTypeService;
        }

        [Authorize]
        public async Task<IActionResult> Read(string storyId, int page = 1, bool isMarked = false)
        {
            isMarked = await this.storyService.IsReadedStory(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier));
            var details = await storyService.GetStoryDetails(storyId, page, isMarked);

            if(details == null)
            {
                return NotFound();
            }

            return this.View(details);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> MarkAsReaded(string storyId)
        {
            var isMarked = await this.storyService.MarkAsReaded(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return RedirectToAction(nameof(Read), new { storyId = storyId, page = 1, isMarked });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(string storyId)
        {

            var model = await this.storyService.GetStory(storyId);

            if (await this.storyService.IsStoryCreatorTheCurrentUser(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            return View(await this.storyService.AddAllGenresAndStoryTypes(model));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(string storyId, string creatorId, StoryEditFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.StoryCreatorUserId = creatorId;
                return View(await this.storyService.AddAllGenresAndStoryTypes(model));
            }
            await this.storyService.Edit(model);


            return RedirectToAction(nameof(Read), new { storyId });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View(await this.storyService.AddAllGenresAndStoryTypes<StoryFormViewModel>());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(StoryFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(await this.storyService.AddAllGenresAndStoryTypes(model));
            }

            await this.storyService.CreateStory(model, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return RedirectToAction(nameof(All));
        }


        [Authorize]
        public async Task<IActionResult> All(string type, string genre, StoryFilterBoxViewModel model)
        {
            return await GetResult(model, await this.storyService.GetAll(model.Genre, model.Type));
        }



        [Authorize]
        public async Task<IActionResult> MyStories(string type, string genre, StoryFilterBoxViewModel model)
        {
            return await GetResult(model, await this.storyService.GetMine(User.FindFirstValue(ClaimTypes.NameIdentifier), model.Genre, model.Type));
        }

        [Authorize]
        public async Task<IActionResult> Readed(string type, string genre, StoryFilterBoxViewModel model)
        {

            return await GetResult(model, await this.storyService.GetReaded(User.FindFirstValue(ClaimTypes.NameIdentifier), model.Genre, model.Type));
        }

        [Authorize]
        public async Task<IActionResult> Search(StoryFilterBoxViewModel model, string? search = null)
        {
            var result = await GetResult(model, await this.storyService.GetSearched(model.Search, model.Genre, model.Type));
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(string storyId)
        {
            if (await this.storyService.IsStoryCreatorTheCurrentUser(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            await this.storyService.DeleteStory(storyId);

            return RedirectToAction(nameof(All));
        }

        private async Task<IActionResult> GetResult(StoryFilterBoxViewModel model, List<StoryFilterCardViewModel> stories)
        {
            var genres = await this.genreService.GetAll();
            var types = await this.storyTypeService.GetAll();

            var outputModel = new StoryFilterBoxViewModel()
            {
                Cards = stories,
                Genres = genres.ToList(),
                StoryTypes = types.ToList(),
                Genre = model.Genre,
                Type = model.Type
            };

            return View(outputModel);
        }
    }
}

Tellers/Tellers.App/Views/Story/Read.cshtml
@using System.Security.Claims;
@using Tellers.Services.Interfaces;
@using Tellers.ViewModels.Story;
@model StoryDetailsViewModel
@inject IUserService userService

<div class="container align-content-center" style="margin-top: 10rem">
    <main role="main" class="pb-3 embed-responsive">
        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark d-inline-flex col-12">
            <div class="col-md-6 px-0 ">
                <h1 class="display-4 font-italic">@Model.Title</h1>
                <h3 class="font-italic">
                    Author:
                    @if (string.IsNullOrEmpty(Model.ExternalAuthorName) == false)
                    {
                        @($"{Model.ExternalAuthorName} (EXTERNAL AUTHOR)")
                        ;
                    }
                    else if (await userService.HasRole(Model.CreatorUserId, RoleNames.MasterAdminRoleName) ||
                    await userService.HasRole(Model.CreatorUserId, RoleNames.AdminRoleName) ||
                    await userService.HasRole(Model.CreatorUserId, RoleNames.ModeratorRoleName))
                    {
                        @("Tellers team")
                        ;
                    }
                    else
                    {
                        @((Model.CreatorFirstName == null ? string.Empty :
                            Model.CreatorFirstName +
                            (Model.CreatorMiddleName == null ? string.Empty : $" {Model.CreatorMiddleName}") +
                            (Model.CreatorLastName == null ? string.Empty : $" {Model.CreatorLastName}") +
                            (Model.CreatorPseudonym == null ? string.Empty : $" - {Model.CreatorPseudonym}")) == string.Empty
                            ?
                            (Model.CreatorUsername == null ? "Unknown post creator." : Model.CreatorUsername)
                            :
                            (Model.CreatorFirstName == null ? string.Empty :
                            Model.CreatorFirstName +
                            (Model.CreatorMiddleName == null ? string.Empty : $" {Model.CreatorMiddleName}") +
                            (Model.CreatorLastName == null ? string.Empty : $" {Model.CreatorLastName}") +
                            (Model.CreatorPseudonym == null ? string.Empty : $" - {Model.CreatorPseudonym}")))
                    }
                </h3>
                <span class="badge rounded-pill bg-success">Story type: @Model.StoryType</span>

                @if (Model.Genres.Count() > 0)
                {
                    @foreach (var genre in Model.Genres)
                    {
                        <span class="badge rounded-pill bg-warning text-black">@genre</span>
                    }
                }
                <p class="lead my-3">@Model.StorySummary</p>
                <p class="lead mb-0 blog-post-meta" style="margin-top: 5em">

                    <a asp-action="Info" asp-controller="Profile" asp-route-profileId="@Model.CreatorId" >
                        <img class="rounded-circle shadow-1-strong me-3"
                             src="@(string.IsNullOrWhiteSpace(Model.CreatorPictureUrl) == false ? Model.CreatorPictureUrl : "/images/profilePicDefault.png")" alt="avatar" width="65"
                             height="65" />
                    </a>

                    by
                    @((Model.CreatorFirstName == null ? string.Empty :
                        Model.CreatorFirstName +
                        (Model.CreatorMiddleName == null ? string.Empty : $" {Model.CreatorMiddleName}") +
                        (Model.CreatorLastName == null ? string.Empty : $" {Model.CreatorLastName}") +
                        (Model.CreatorPseudonym == null ? string.Empty : $" - {Model.CreatorPseudonym}")) == string.Empty
                        ?
                        (Model.CreatorUsername == null ? "Unknown post creator." : Model.CreatorUsername)
                        :
                        (Model.CreatorFirstName == null ? string.Empty :
                        Model.CreatorFirstName +
                        (Model.CreatorMiddleName == null ? string.Empty : $" {Model.CreatorMiddleName}") +
                        (Model.CreatorLastName == null ? string.Empty : $" {Model.CreatorLastName}") +
                        (Model.CreatorPseudonym == null ? string.Empty : $" - {Model.CreatorPseudonym}")))


                </p>
                posted on: @Model.Day-@Model.Month-@Model.Year



                <form method="post" style="margin-top: 3rem">

                    @if (User.IsInRole(RoleNames.MasterAdminRoleName) ||
                    User.IsInRole(RoleNames.AdminRoleName) ||
                    User.IsInRole(RoleNames.ModeratorRoleName) ||
                    User.Identity.Name == Model.CreatorUsername)
                    {
                        <button class="btn btn-outline-danger btn-lg px-4 gap-3" asp-action="Delete" asp-controller="Story" asp-route-storyId="@Model.StoryId" style="background-color: none">
                            Delete
                        </button>

                    }
                    @if (User.Identity.Name != Model.CreatorUsername)
                    {
                        if (Model.IsMarkedAsReaded)
                        {
                            <button class="btn btn-info btn-lg px-4 gap-3" asp-action="MarkAsReaded" asp-controller="Story" asp-route-storyId="@Model.StoryId" style="background-color: none">
                                Readed
                            </button>
                        }
                        else
                        {
                            <button class="btn btn-outline-info btn-lg px-4 gap-3" asp-action="MarkAsReaded" asp-controller="Story" asp-route-storyId="@Model.StoryId" style="background-color: none">
                                Mark as readed
                            </button>
                        }
                    }

                    @if (User.Identity.Name == Model.CreatorUsername)
                    {
                        <a class="btn btn-outline-success btn-lg px-4 gap-3" asp-action="Edit" asp-controller="Story" asp-route-storyId="@Model.StoryId" style="background-color: none">
                            Edit
                        </a>
                    }
                </form>
                
            </div>
            <img src="@(Model.BookCoverPicture ?? "/images/no-book-cover-available.jpg")" class="img-fluid col-md-6 overflow-hidden" alt="book cover">
        </div>

        <div class="ratio ratio-16x9 viewPDF" style="margin-top: 0.5em;">
        </div>
    </main>
    <section style="background-color: #e7effd; padding-bottom: 3em; padding-top: 2em">

        <nav aria-label="...">
            <ul class="pagination pagination-sm justify-content-center">
                @for (int i = 1; i <= (int)Math.Ceiling(Model.TotalRevues / 5.0); i++)
                {
                    @if(i == Model.Page)
                    {
                        <li class="page-item active" aria-current="page">
                        <a class="page-link" asp-action="Read" asp-controller="Story" asp-route-storyId="@Model.StoryId" asp-route-page="@i" asp-fragment="revues">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item" aria-current="page">
                            <a class="page-link" asp-action="Read" asp-controller="Story" asp-route-storyId="@Model.StoryId" asp-route-page="@i" asp-fragment="revues">@i</a>
                        </li>
                    }

                }
            </ul>
        </nav>

        <h3 class="display-6 font-italic justify-content-center text-center fw-bold" id="revues">Revues:</h3>
        
        <partial name="_ReadRevuesPartial.cshtml" model="@Model.Revues" />

        <nav aria-label="...">
            <ul class="pagination pagination-sm justify-content-center">
                @for (int i = 1; i <= (int)Math.Ceiling(Model.TotalRevues / 5.0); i++)
                {
                    @if (i == Model.Page)
                    {
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" asp-action="Read" asp-controller="Story" asp-route-storyId="@Model.StoryId" asp-route-page="@i" asp-fragment="revues">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item" aria-current="page">
                            <a class="page-link" asp-action="Read" asp-controller="Story" asp-route-storyId="@Model.StoryId" asp-route-page="@i" asp-fragment="revues">@i</a>
                        </li>
                    }

                }
            </ul>
        </nav>

        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center" style="margin-top: 5em; margin-bottom: 3em">
            <a type="button" class="btn btn-outline-success btn-lg px-4 gap-3" asp-controller="Revue" asp-action="Create" asp-route-storyId="@Model.StoryId">Аdd a Revue</a>
        </div>
        <div></div>
    </section>

</div>
<label id="pdfUrl" hidden>@Model.PdfFileUrl</label>
@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfobject/2.2.8/pdfobject.min.js" integrity="sha512-MoP2OErV7Mtk4VL893VYBFq8yJHWQtqJxTyIAsCVKzILrvHyKQpAwJf9noILczN6psvXUxTr19T5h+ndywCoVw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">

        let label = document.getElementById("pdfUrl");
        let url = label.textContent;

        let urlEmbeding = `https://docs.google.com/gview?url=${url}&embedded=true`;
        if (url.includes('drive.google.com')) {
            urlEmbeding = url;
        }

        if (PDFObject.supportsPDFs) {
            PDFObject.embed(urlEmbeding + "#toolbar=0&pagemode=none", ".viewPDF",)
        } else {
            let result = confirm("This browser does not support PDFObject. Do you want to stay and read story summury?");

            if (!result) {
                window.location.href = "/";
            }
        }
    </script>
    <script type="text/javascript">
        'use strict'
        let elementsNumber = document.querySelectorAll(".starRatingLable").length;

        for (let i = 1; i <= elementsNumber; i++) {
            let rating = Number(document.getElementById(`ratingStar${i}`).textContent);

            if (rating >= 1) {
                document.querySelector(`.fa.fa-star.oneStar${i}`).classList.add("checked");
            }
            if (rating >= 2) {
                document.querySelector(`.fa.fa-star.twoStar${i}`).classList.add("checked");
            }
            if (rating >= 3) {
                document.querySelector(`.fa.fa-star.threeStar${i}`).classList.add("checked");
            }
            if (rating >= 4) {
                document.querySelector(`.fa.fa-star.fourStar${i}`).classList.add("checked");
            }
            if (rating >= 5) {
                document.querySelector(`.fa.fa-star.fiveStar${i}`).classList.add("checked");
            }
        }




    </script>

}
}

@section Styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

Tellers/Tellers.App/Views/Story/_ReadRevuesPartial.cshtml
@using System.Security.Claims;
@using Tellers.DataModels;
@using Tellers.Services.Interfaces;
@using Tellers.ViewModels.Revues;
@model IEnumerable<ReadRevueViewModel>
@inject IUserService userService


<div class="container my-5 py-5 text-dark">

    @if (Model.Count() == 0 || Model == null)
    {
        <p class="display-6 font-italic justify-content-center text-center" id="revues">No revues yet...</p>
    }
    else
    {
        
        int i = 1;
        @foreach (var revue in Model)
        {
            <div class="row d-flex justify-content-center" style="margin-top: 3em">
                <div class="col-md-11 col-lg-9 col-xl-7">
                    <div class="d-flex flex-start">
                        <a asp-action="Info" asp-controller="Profile" asp-route-profileId="@revue.CreatorId">
                            <img class="rounded-circle shadow-1-strong me-3"
                         src="@(string.IsNullOrWhiteSpace(revue.CreatorPictureUrl) == false ? revue.CreatorPictureUrl : "/images/profilePicDefault.png")" alt="avatar" width="65"
                         height="65" />
                        </a>
                        <div class="card w-100">
                            <div class="card-body p-4">
                                <div class="">
                                    <h5>
                                        <a asp-action="" asp-controller="">
                                            @if (await userService.HasRole(revue.CreatorUserId, RoleNames.MasterAdminRoleName) ||
                                           await userService.HasRole(revue.CreatorUserId, RoleNames.AdminRoleName) ||
                                           await userService.HasRole(revue.CreatorUserId, RoleNames.ModeratorRoleName))
                                            {
                                                @("Tellers team")
                                            }
                                            else
                                            {
                                                @((revue.CreatorFirstName == null ? string.Empty :
                                                    revue.CreatorFirstName +
                                                    (revue.CreatorMiddleName == null ? string.Empty : $" {revue.CreatorMiddleName}") +
                                                    (revue.CreatorLastName == null ? string.Empty : $" {revue.CreatorLastName}") +
                                                    (revue.CreatorPseudonym == null ? string.Empty : $" - {revue.CreatorPseudonym}")) == string.Empty
                                                    ?
                                                    (revue.CreatorUsername == string.Empty ? "Unknown post creator." : revue.CreatorUsername)
                                                    :
                                                    (revue.CreatorFirstName == null ? string.Empty :
                                                    revue.CreatorFirstName +
                                                    (revue.CreatorMiddleName == null ? string.Empty : $" {revue.CreatorMiddleName}") +
                                                    (revue.CreatorLastName == null ? string.Empty : $" {revue.CreatorLastName}") +
                                                    (revue.CreatorPseudonym == null ? string.Empty : $" - {revue.CreatorPseudonym}")))
                                            }
                                        </a>
                                    </h5>
                                    <span class="fa fa-star oneStar@(i)"></span>
                                    <span class="fa fa-star twoStar@(i)"></span>
                                    <span class="fa fa-star threeStar@(i)"></span>
                                    <span class="fa fa-star fourStar@(i)"></span>
                                    <span class="fa fa-star fiveStar@(i)"></span>
                                    <label id="ratingStar@(i++)" class="starRatingLable" hidden>@revue.Rating</label>
                                    <p class="small">@($"{revue.CreatedOn.ToString("dd")}-{revue.CreatedOn.ToString("MMMM")}-{revue.CreatedOn.ToString("yyyy")}")</p>
                                    <p>
                                        @revue.Text
                                    </p>

                                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                                        @if (User.IsInRole(RoleNames.MasterAdminRoleName) ||
                                       User.IsInRole(RoleNames.AdminRoleName) ||
                                       User.IsInRole(RoleNames.ModeratorRoleName) ||
                                       User.Identity.Name == revue.CreatorUsername)
                                        {
                                            <form method="post" style="margin-top: 3rem">
                                                <button class="btn btn-outline-success btn-lg px-4 gap-3" asp-action="Delete" asp-controller="Revue" asp-route-revueId="@revue.Id" asp-route-storyId="@revue.StoryId" asp-fragment="revues" style="background-color: none">
                                                    Delete
                                                </button>
                                            </form>
                                        }
                                        @if (User.Identity.Name == revue.CreatorUsername)
                                        {
                                            <a class="btn btn-outline-warning btn-lg px-4" type="button" asp-action="Edit" asp-controller="Revue" asp-route-revueId="@revue.Id" asp-route-storyId="@revue.StoryId" asp-route-userId="@revue.CreatorUserId" style="background-color: none; margin-top: 3rem">
                                                Edit
                                            </a>
                                        }
                                    </div>
                                    <div class="d-inline-flex">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

            
    }

</div>