Tellers/Tellers.App/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System.Security.Claims;
using Tellers.Services.Interfaces;
using Tellers.ViewModels.Profiles;

namespace Tellers.App.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProfileService profileService;

        public ProfileController(IProfileService profileService)
        {
            this.profileService = profileService;
        }

        [Authorize]
        public async Task<IActionResult> Info(string profileId)
        {
            return View(await this.profileService.GetProfileInfo(profileId, User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }
    }
}

Tellers/Tellers.App/Controllers/StoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using Tellers.Services.Interfaces;
using Tellers.ViewModels.Story;

namespace Tellers.App.Controllers
{
    public class StoryController : Controller
    {
        private readonly IStoryService storyService;
        private readonly IGenreService genreService;
        private readonly IStoryTypeService storyTypeService;

        public StoryController(
            IStoryService storyService,
            IGenreService genreService,
            IStoryTypeService storyTypeService)
        {
            this.storyService = storyService;
            this.genreService = genreService;
            this.storyTypeService = storyTypeService;
        }

        [Authorize]
        public async Task<IActionResult> Read(string storyId, int page = 1, bool isMarked = false)
        {
            isMarked = await this.storyService.IsReadedStory(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier));
            var details = await storyService.GetStoryDetails(storyId, page, isMarked);

            if(details == null)
            {
                return NotFound();
            }

            return this.View(details);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> MarkAsReaded(string storyId)
        {
            var isMarked = await this.storyService.MarkAsReaded(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return RedirectToAction(nameof(Read), new { storyId = storyId, page = 1, isMarked });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(string storyId)
        {

            var model = await this.storyService.GetStory(storyId);

            if (await this.storyService.IsStoryCreatorTheCurrentUser(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            return View(await this.storyService.AddAllGenresAndStoryTypes(model));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(string storyId, string creatorId, StoryEditFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.StoryCreatorUserId = creatorId;
                return View(await this.storyService.AddAllGenresAndStoryTypes(model));
            }
            await this.storyService.Edit(model);


            return RedirectToAction(nameof(Read), new { storyId });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View(await this.storyService.AddAllGenresAndStoryTypes<StoryFormViewModel>());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(StoryFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(await this.storyService.AddAllGenresAndStoryTypes(model));
            }

            await this.storyService.CreateStory(model, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return RedirectToAction(nameof(All));
        }


        [Authorize]
        public async Task<IActionResult> All(string type, string genre, StoryFilterBoxViewModel model)
        {
            return await GetResult(model, await this.storyService.GetAll(model.Genre, model.Type));
        }



        [Authorize]
        public async Task<IActionResult> MyStories(string type, string genre, StoryFilterBoxViewModel model)
        {
            return await GetResult(model, await this.storyService.GetMine(User.FindFirstValue(ClaimTypes.NameIdentifier), model.Genre, model.Type));
        }

        [Authorize]
        public async Task<IActionResult> Readed(string type, string genre, StoryFilterBoxViewModel model)
        {

            return await GetResult(model, await this.storyService.GetReaded(User.FindFirstValue(ClaimTypes.NameIdentifier), model.Genre, model.Type));
        }

        [Authorize]
        public async Task<IActionResult> Search(StoryFilterBoxViewModel model, string? search = null)
        {
            var result = await GetResult(model, await this.storyService.GetSearched(model.Search, model.Genre, model.Type));
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(string storyId)
        {
            if (await this.storyService.IsStoryCreatorTheCurrentUser(storyId, User.FindFirstValue(ClaimTypes.NameIdentifier)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            await this.storyService.DeleteStory(storyId);

            return RedirectToAction(nameof(All));
        }

        private async Task<IActionResult> GetResult(StoryFilterBoxViewModel model, List<StoryFilterCardViewModel> stories)
        {
            var genres = await this.genreService.GetAll();
            var types = await this.storyTypeService.GetAll();

            var outputModel = new StoryFilterBoxViewModel()
            {
                Cards = stories,
                Genres = genres.ToList(),
                StoryTypes = types.ToList(),
                Genre = model.Genre,
                Type = model.Type
            };

            return View(outputModel);
        }
    }
}

Tellers/Tellers.App/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Tellers.Services.Interfaces;
using Tellers.Utilities;
using Tellers.ViewModels.User;

namespace Tellers.App.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User?.Identity?.IsAuthenticated ?? false)
            {
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).ReplaceControllerSuffix());
            }
            var model = new LoginViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if(ModelState.IsValid == false)
            {
                return View(model);
            }
            var result = await userService.Login(model.UserName, model.Password, model.RememberMe);

            if (result.IsSucceeded)
            {
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).ReplaceControllerSuffix());
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(model);
            }

        }

        [HttpGet]
        public IActionResult Register()
        {
            if (User?.Identity?.IsAuthenticated ?? false)
            {
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).ReplaceControllerSuffix());
            }
            var model = new RegisterViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            var result = await userService.Register(model.Email, model.UserName, model.Password, model.AcceptedAgreement);

            if(result.IsSucceeded)
            {
                return RedirectToAction(nameof(Login));
            }
            else
            {
                ModelState.AddModelError(string.Empty, result.Message);
                return View(model);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            var result = await userService.Logout();

            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).ReplaceControllerSuffix());
        }
    }
}

Tellers/Tellers.App/Views/Shared/CarouselGalleryPartial.cshtml
@using Tellers.Utilities.Interfaces;
@using Tellers.ViewModels.Story;
@model IViewModelInfoBox<List<StoryCardViewModel>>

@if(Model.ViewModel == null || Model.ViewModel.Count == 0)
{
    <div class="px-4 py-1 text-center" style="background-color: aliceblue; margin-top: 2rem">
        <p class="display-4 fw-bold">No stories yet :(</p>
    </div>
}
else
{
    <!-- Carousel wrapper -->

    <div id="carouselMultiItemExample@(Model.ModelIndicator)"
     class="carousel slide carousel-dark text-center"
     data-bs-ride="carousel">



        <!-- Inner -->
        <div class="carousel-inner py-4">
            <!-- Single item (contains 3 cards)-->
            @for (int i = 0; i < 3; i++)
            {
                var classElement = i == 0 ? "active" : string.Empty;
                var noBookCover = "/images/no-book-cover-available.jpg";

                <div class="carousel-item @classElement">
                    <div class="container">
                        <div class="row">

                            @for (int j = i * 3; j < (i * 3) + 3; j++)
                            {
                                <div class="col-lg-4">
                                    <div class="card">
                                        <img src="@(Model?.ViewModel[j]?.BookCoverPicture ?? noBookCover)"
                                 class="card-img-top"
                                 alt="Waterfall" />
                                        <div class="card-body">
                                            <h5 class="card-title">@(Model?.ViewModel[j]?.Title ?? "No title")</h5>
                                            <p class="card-text"></p>
                                            @if (User?.Identity?.IsAuthenticated ?? false)
                                            {
                                                <a asp-controller="Story" asp-action="Read" asp-route-storyId="@Model.ViewModel[j].Id" class="btn btn-primary">Read it</a>
                                            }
                                        </div>
                                    </div>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            }
        </div>

        <!-- Inner -->
        <!-- Controls -->
        <div class="d-flex justify-content-center mb-4">
            <button class="carousel-control-prev position-relative"
                type="button"
                data-bs-target="#carouselMultiItemExample@(Model.ModelIndicator)"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next position-relative"
                type="button"
                data-bs-target="#carouselMultiItemExample@(Model.ModelIndicator)"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <!-- Carousel wrapper -->
}

Tellers/Tellers.App/Views/Shared/FooterPartial.cshtml
<footer class="text-center text-lg-start bg-white text-muted" style="background-color: cornflowerblue; margin-top: 10rem">

    <!-- Section: Links  -->
    <section class="border-top" style="background-color: lightblue">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3 text-secondary"></i>TELLERS COMPANY
                    </h6>
                    <p>
                        The web site is created for SoftUni course project defence. It is a site where people can share their stories with the others or just to read diffrent type of stories.
                    </p>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3 text-secondary"></i>Sliven, 8800, BG</p>
                    <p>
                        <i class="fas fa-envelope me-3 text-secondary"></i>tellers@mail.com
                    </p>
                    <p><i class="fas fa-phone me-3 text-secondary"></i>+359 887 88 22 55</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
        © 2022 Copyright:
        <a class="text-reset fw-bold" href="/">Tellers</a>
        <div><a class="fw-bold" asp-action="Terms" asp-controller="Home">Terms</a></div>
    </div>
    <!-- Copyright -->
</footer>

Tellers/Tellers.App/Views/Shared/_Layout_GuestUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightblue">
            <!-- Container wrapper -->
            <div class="container">
                <!-- Navbar brand -->
                <a class="navbar-brand me-2" href="/">
                    <img src="~/images/storyTelling.jpg"
                         height="50"
                         alt="Tellers Logo"
                         loading="lazy"
                         style="margin-top: -1px;" 
                         class="rounded-circle"/>
                </a>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarButtonsExample">
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Tellers</a>
                        </li>
                    </ul>
                    <!-- Left links -->

                    <div class="d-flex align-items-center collapse">
                        <a type="button" class="btn btn-link px-3 me-2" asp-action="Login" asp-controller="User">
                            Login
                        </a>
                        <a type="button" class="btn btn-outline-primary me-3" asp-action="Register" asp-controller="User">
                            Sign up for free
                        </a>
                    </div>
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

    </header>

    @*<iframe src="https://drive.google.com/file/d/1kYufcQIi_pIlITHu3OY3figMgPdBHHLK/preview" class="embed-responsive-item"></iframe>*@
    @RenderBody();

    <!-- Footer -->
    <partial name="FooterPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tellers/Tellers.App/Views/Shared/_Layout_LoggedUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-light fixed-top" style="background-color: lightblue">
            <div class="container-fluid">
                <button class="navbar-toggler rounded-1 border-2" style="border-color: whitesmoke" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBlueNavbar" aria-controls="offcanvasBlueNavbar">
                    <span class="navbar-toggler-icon text-white"></span>
                </button>
                <a class="navbar-brand me-2" href="/">
                    <img src="~/images/storyTelling.jpg"
                         height="50"
                         alt="Tellers Logo"
                         loading="lazy"
                         style="margin-top: -1px;"
                         class="rounded-circle" />
                </a>

                <div class="offcanvas offcanvas-start " tabindex="-1" id="offcanvasBlueNavbar" aria-labelledby="offcanvasBlueNavbarLabel">
                    <div class="offcanvas-header" style="background-color: lightblue">
                        <h5 class="offcanvas-title" id="offcanvasBlueNavbarLabel">Wellcome@(User?.Identity?.Name == null ? "!" : $", {User.Identity.Name}")</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body " style="background-color: aliceblue">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="All" asp-controller="Story">All stories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Readed" asp-controller="Story">Readed stories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Create" asp-controller="Story">Share your story</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-dark" asp-action="Info" asp-controller="Profile">My Profile</a></li>
                                    <li><a class="dropdown-item" asp-action="MyStories" asp-controller="Story">My stories</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#">My friends</a></li>
                                    <li><a class="dropdown-item" href="#">My follows</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li style="background-color:antiquewhite"><p style="margin-left: 1rem;">Number of followers:</p></li>
                                    <li style="background-color:antiquewhite"><p style="margin-left: 1rem;">Total number of my stories: </p></li>
                                    <li style="background-color:antiquewhite"><p style="margin-left: 1rem;">Total number of readed stories: </p></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="d-flex mt-3" role="search" id="searchForm" method="get">

                            <input class="form-control me-2" name="searchText" type="search" placeholder="Search by title" aria-label="Search" id="searchText" />
                            <button class="btn btn-primary" id="searchButton">
                                Search
                            </button>
                        </form>

                        @if ((User?.IsInRole(RoleNames.MasterAdminRoleName) ?? false) ||
                        (User?.IsInRole(RoleNames.AdminRoleName) ?? false) ||
                        (User?.IsInRole(RoleNames.ModeratorRoleName) ?? false))
                        {
                            <form method="post" style="margin-top: 3rem">
                                <button class="btn btn-primary" asp-area="Admin" asp-action="Index" asp-controller="Home">
                                    Admin panel
                                </button>
                            </form>
                        }
                        <form method="post" style="margin-top: 3rem">
                            <button class="btn btn-success" asp-action="Logout" asp-controller="User">
                                Logout
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>


    @RenderBody()

    <partial name="FooterPartial" />

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript">
        let form = document.getElementById("searchForm");

        form.addEventListener("submit", (e) => {
            e.preventDefault();
            let formData = new FormData(e.currentTarget);

            let { searchText } = Object.fromEntries(formData);

            window.location.href = `/Story/Search?search=${searchText}`;
        })
    </script>
</body>
</html>